version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://flask-app:5000
    depends_on:
      - flask-app

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

